import 'package:flutter/material.dart';
import 'dart:math';

void main() {
  runApp(MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  // Hard-coded proof-of-concept questions list:
  QuestionsList questionsList = QuestionsList({
    // questions generated by AI
    Question("What’s been the best part of your week so far?"),
    Question("Are you binge-watching or reading anything good right now?"),
    Question("Any fun plans for the weekend, or are you just taking it easy?"),
    Question("What’s your most controversial food opinion?"),
    Question(
      "If you could instantly become an expert in any subject, what would it be?",
    ),
    Question("What’s the most useless talent you have?"),
    Question("What’s something you’re looking forward to this year?"),
    Question("What’s the best piece of advice you’ve ever actually followed?"),
    Question("What is your absolute favorite way to spend a rainy day?"),
  });

  Question currentQuestion = Question(
    "Are you ready to start?\n(The button you press for this question doesn't matter lol.)",
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: [
              Container(
                decoration: BoxDecoration(
                  color: Colors.lightBlue,
                  borderRadius: BorderRadius.circular(10),
                ),
                width: MediaQuery.sizeOf(context).width * 0.8,
                child: Padding(
                  padding: EdgeInsetsGeometry.all(10),
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text(
                        "Question:",
                        style: TextStyle(
                          color: Colors.white,
                          fontWeight: FontWeight.bold,
                        ),
                        textAlign: TextAlign.center,
                      ),
                      Text(
                        currentQuestion.questionText,
                        style: TextStyle(color: Colors.white),
                        textAlign: TextAlign.center,
                      ),
                    ],
                  ),
                ),
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Container(
                    padding: EdgeInsets.all(20),
                    child: ElevatedButton(
                      // pass button
                      onPressed: () {
                        setState(() {
                          currentQuestion = questionsList.getRandomQuestion();
                        });
                      },
                      child: Text("Pass"),
                    ),
                  ),
                  Container(
                    padding: EdgeInsets.all(20),
                    child: ElevatedButton(
                      // answer button
                      onPressed: () {
                        setState(() {
                          currentQuestion.answer(null);
                          currentQuestion = questionsList.getRandomQuestion();
                        });
                      },
                      child: Text("Answer"),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class Question {
  bool _answered = false;
  final String _questionText;
  String? _answerText;

  bool get isAnswered => _answered;
  String get questionText => _questionText;
  String? get answerText => _answerText;

  Question(this._questionText);
  void answer(String? answer) {
    if (!_answered) {
      _answerText = answer;
      _answered = true;
    }
  }
}

class QuestionsList {
  var questions = <Question>{};

  QuestionsList(Set<Question>? questions) {
    if (questions != null) {
      this.questions.addAll(questions);
    }
  }

  Question getRandomQuestion() {
    final random = Random();
    Question randomQuestion;
    do {
      randomQuestion = questions.toList()[random.nextInt(questions.length)];
    } while (randomQuestion.isAnswered);

    return randomQuestion;
  }
}
